all: q1a1 q1a2 q1b1 q1b2

q1a1: q1a1.c
	gcc -o q1a1 q1a1.c

q1a2: q1a2.c
	gcc -o q1a2 q1a2.c

q1b1: q1b1.c
	gcc -o q1b1 q1b1.c

q1b2: q1b2.c
	gcc -o q1b2 q1b2.c

clean:
	rm q1a1 q1a2 q1b1 q1b2